In [23]:
# What is a Python library? Why do we use Python libraries?

'''
A library is a collection of code that makes everyday tasks more efficient. Using Seaborn, for example, you can generate visualisations with just one line of code. To create a chart from an object, you’d have to write a lot of code without a library like this. Python is a popular choice for data analysis because of its extensive library of tools for manipulating, visualising, and training machine learning models.
Python libraries are collections of pre-written code and functions that extend the capabilities of the Python programming language. They provide a wide range of tools and modules for various tasks, making it easier for developers to work on specific tasks without reinventing the wheel.
The Python Standard Library contains the exact syntax, semantics, and tokens of Python. It contains built-in modules that provide access to basic system functionality like I/O and some other core modules. Most of the Python Libraries are written in the C programming language. The Python standard library consists of more than 200 core modules. All these work together to make Python a high-level programming language. Python Standard Library plays a very important role. Without it, the programmers can’t have access to the functionalities of Python. 


'''



'\nA library is a collection of code that makes everyday tasks more efficient. Using Seaborn, for example, you can generate visualisations with just one line of code. To create a chart from an object, you’d have to write a lot of code without a library like this. Python is a popular choice for data analysis because of its extensive library of tools for manipulating, visualising, and training machine learning models.\nPython libraries are collections of pre-written code and functions that extend the capabilities of the Python programming language. They provide a wide range of tools and modules for various tasks, making it easier for developers to work on specific tasks without reinventing the wheel.\nThe Python Standard Library contains the exact syntax, semantics, and tokens of Python. It contains built-in modules that provide access to basic system functionality like I/O and some other core modules. Most of the Python Libraries are written in the C programming language. The Python sta

In [24]:
# What is the difference between Numpy array and List?

'''NumPy is the fundamental package for scientific computing in Python.
Numpy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences. Numpy is not another programming language but a Python extension module. 
It provides fast and efficient operations on arrays of homogeneous data. 
The list can be homogeneous or heterogeneous.
Element-wise operation is not possible on the list.
Python list is by default 1-dimensional. But we can create an N-Dimensional list. But then too it will be 1 D list storing another 1D list
Elements of a list need not be contiguous in memory.
List stores the address of the elements so the retrieval of the elements is a bit slow compared to the array elements

'''



'NumPy is the fundamental package for scientific computing in Python.\nNumpy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences. Numpy is not another programming language but a Python extension module. \nIt provides fast and efficient operations on arrays of homogeneous data. \nThe list can be homogeneous or heterogeneous.\nElement-wise operation is not possible on the list.\nPython list is by default 1-dimensional. But we can create an N-Dimensional list. But then too it will be 1 D list storing another 1D list\nElements of a list need not be contiguous in memory.\nList stores the address of the elements so the retrieval of the elements is a bit slow compared to the array elements\n\n'

In [25]:
'''Find the shape, size and dimension of the following array?'''


import numpy as np

arr = np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])


# To find the dimension of the array we use ndim

arr.ndim

#  The shape can be found using the shape method
np.shape(arr)



(3, 4)

In [26]:
# we can find the size by using size method
np.size(arr)

12

In [27]:
# Write python code to access the first row of the following array?

arr1 =  [[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]


res = np.array(arr1)
res.ndim


res[0]


array([1, 2, 3, 4])

In [28]:
# 5. How do you access the element at the third row and fourth column from the given numpy array?

a = [[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]

arr = np.array(a)

arr[2][3]




12

In [29]:
# 6. Write code to extract all odd-indexed elements from the given numpy array?

arr = [[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]


a = np.array(arr)

In [30]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11])

In [31]:
#7. How can you generate a random 3x3 matrix with values between 0 and 1?
a =np.random.randint(0,2,size=(3,3)) 


In [32]:
np.matrix(a)

matrix([[0, 1, 0],
        [1, 0, 1],
        [0, 0, 0]])

In [33]:
# 8. Describe the difference between np.random.rand and np.random.randn?


# np.random.rand gives us the random values in the required shape which we provide


a = np.random.rand(3,2)
b = np.random.randn(3,2)

a
b

'''The random.randn() is a numpy library function that returns an array of random samples from the standard normal distribution. 
It allows specified dimensions as an argument and returns an array of specified dimensions. If you don’t provide any argument, it will return the float value. The np.random.randn() function returns all the samples in float form, which are from the univariate “normal” (Gaussian) distribution of mean 0 and variance 1.
'''

'The random.randn() is a numpy library function that returns an array of random samples from the standard normal distribution. \nIt allows specified dimensions as an argument and returns an array of specified dimensions. If you don’t provide any argument, it will return the float value. The np.random.randn() function returns all the samples in float form, which are from the univariate “normal” (Gaussian) distribution of mean 0 and variance 1.\n'

In [34]:
b

array([[ 0.09116817,  0.9143452 ],
       [ 0.17632355, -1.31189557],
       [-1.69136775, -0.63589038]])

In [35]:
'''9. Write code to increase the dimension of the following array?
'''


arr = [[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]






In [36]:
np.expand_dims(arr,axis=0) # This syntax can be used to expand the dimensions of the array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [37]:
'''10. How to transpose the following array in NumPy?
'''
arr = [[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]


a = np.array(arr)



In [38]:
a.T # This is used to transpose an array

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [39]:
'''11. Consider the following matrix:

Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


Perform the following operation using Python1
Index wise multiplication
matrix multiplication
add both the matrices
subtract matrix B from A
Divide matrix B by A

'''
x= np.matrix([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
y  = np.matrix([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])


In [43]:
x


matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [49]:
y = np.transpose(y)

In [50]:
# INDEX WISE MULTIPLICATION

x*y

matrix([[ 30,  70, 110],
        [ 70, 174, 278],
        [110, 278, 446]])

In [53]:

#dot product

np.dot(x,y)


matrix([[ 30,  70, 110],
        [ 70, 174, 278],
        [110, 278, 446]])

In [54]:
# Matrix multiplication

np.matmul(x,y)

matrix([[ 30,  70, 110],
        [ 70, 174, 278],
        [110, 278, 446]])

In [58]:
# Matrix Addition

y = np.transpose(y)
x+y

matrix([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]])

In [59]:
# Subtraction

y-x

matrix([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [60]:
# division

x/y

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
'''12.  Which function in Numpy can be used to swap the byte order of an array?'''

'''The ndarray.byteswap() method swaps the bytes of the array elements. It toggles between low-endian and big-endian data representation by returning a byteswapped array, optionally swapped in-place.'''

'The ndarray.byteswap() method swaps the bytes of the array elements. It toggles between low-endian and big-endian data representation by returning a byteswapped array, optionally swapped in-place.'

In [ ]:
'''13.  What is the significance of the np.linalg.inv function?'''

'''Matrices play a crucial role in various mathematical and scientific computations. In many scenarios, finding the inverse of a matrix is essential for solving linear equations, optimization problems, and more. In Python, the numpy library provides a convenient function, np.linalg.inv(), for calculating the inverse of a matrix efficiently. 
    '''

In [ ]:
'''14. What does the np.reshape function do, and how is it used?'''

''' NumPy’s reshape() enables you to change the shape of an array into another compatible shape. Not all shapes are compatible since all the elements from the original array needs to fit into the new array.'''

In [ ]:
'''What is broadcasting in numpy'''

'''The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations.

Broadcasting has certain rules 


When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimension and works its way left. Two dimensions are compatible when

they are equal, or

one of them is 1.


'''